#! /bin/sh

### BEGIN INIT INFO
# Provides:          psi-dns-capture
# Required-Start:    $network
# Required-Stop:     $network
# Should-Start:      
# Should-Stop:       
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Starts the Psiphon 3 DNS capture
# Description:       Psiphon 3 statistics need to correlate target IP addresses
#                    to DNS requests to be able to report on top web sites accessed
#                    through Psiphon 3.
### END INIT INFO

PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
DAEMON=/usr/sbin/tcpdump
DAEMON_ARGS="-Z www-data -w /var/cache/dns-pcaps/dnspcap_%Y%m%d-%H%M%S.pcap -G 3600 -z gzip -n -i eth0 port 53"
NAME=psi-dns-capture
DESC="Psiphon 3 DNS capture"
test -x $DAEMON || exit 0

PIDFILE=/var/run/$NAME.pid

set -e

case "$1" in
  start)
	echo -n "Starting $DESC: "
	mkdir -p /var/cache/dns-pcaps
	chown www-data:www-data /var/cache/dns-pcaps
	start-stop-daemon -S -q -p $PIDFILE -b -m -x $DAEMON -- $DAEMON_ARGS
	echo "$NAME."
	;;
  stop)
	echo -n "Stopping $DESC: "
	start-stop-daemon -K -q -p $PIDFILE --oknodo
	echo "$NAME."
	;;
  restart)
	$0 stop
	sleep 1
	$0 start
	;;
  *)
	N=/etc/init.d/$NAME
	echo "Usage: $N {start|stop|restart}" >&2
	exit 1
	;;
esac

exit 0

