//
//  EmbeddedValues.h
//  Psiphon
//
//  Created by eugene on 2013-10-09.
//  Copyright (c) 2013 Psiphon. All rights reserved.
//

FOUNDATION_EXPORT NSString *const PROPAGATION_CHANNEL_ID;
FOUNDATION_EXPORT NSString *const SPONSOR_ID;
FOUNDATION_EXPORT NSString *const CLIENT_VERSION;
FOUNDATION_EXPORT NSString *const CLIENT_PLATFORM;
FOUNDATION_EXPORT NSString *const EMBEDDED_SERVER_LIST[];
FOUNDATION_EXPORT NSString *const REMOTE_SERVER_LIST_URL;
FOUNDATION_EXPORT NSString *const REMOTE_SERVER_LIST_SIGNATURE_PUBLIC_KEY;
FOUNDATION_EXPORT NSString *const FEEDBACK_ENCRYPTION_PUBLIC_KEY;
FOUNDATION_EXPORT NSString *const INFO_LINK_URL;
FOUNDATION_EXPORT NSString *const PROXIED_WEB_APP_HTTP_AUTH_USERNAME;
FOUNDATION_EXPORT NSString *const PROXIED_WEB_APP_HTTP_AUTH_PASSWORD;
