//
//  PsiphonConstants.h
//  Psiphon
//
//  Created by eugene on 2013-10-09.
//  Copyright (c) 2013 Psiphon. All rights reserved.
//

FOUNDATION_EXPORT NSString *const PROPAGATION_CHANNEL_ID;
FOUNDATION_EXPORT BOOL IS_DEBUG; // may be changed by application
FOUNDATION_EXPORT NSString* const SERVER_ENTRY_FILENAME;
FOUNDATION_EXPORT NSString* const LAST_CONNECTED_FILENAME;
FOUNDATION_EXPORT const int CLIENT_SESSION_ID_SIZE_IN_BYTES;
FOUNDATION_EXPORT const int SOCKS_PORT;
FOUNDATION_EXPORT const int DEFAULT_WEB_SERVER_PORT;
FOUNDATION_EXPORT NSString* const RELAY_PROTOCOL;
FOUNDATION_EXPORT NSString* const LOG_ENTRY_NOTIFICATION_KEY;
FOUNDATION_EXPORT NSString* const NEW_LOG_ENTRY_POSTED;
FOUNDATION_EXPORT const int SSH_CONNECT_TIMEOUT_SECONDS;
FOUNDATION_EXPORT const int REACHABILITY_MAX_NUM_OPERATIONS;
FOUNDATION_EXPORT const float REACHABILITY_CONNECT_TIMEOUT_SECONDS;
FOUNDATION_EXPORT const float REACHABILITY_SELECTOR_POLL_SECONDS;
FOUNDATION_EXPORT const int SECONDS_BETWEEN_SUCCESSFUL_REMOTE_SERVER_LIST_FETCH;
FOUNDATION_EXPORT const int SECONDS_BETWEEN_UNSUCCESSFUL_REMOTE_SERVER_LIST_FETCH;


